apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-web-app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: subconcealed-odessa-unsteadfastly.ngrok-free.dev # ngrok http 80
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-web-app-service
            port:
              number: 80
